version: '3'
services:
  app:
    container_name: api
    build: 
      context: .
      dockerfile: dev.Dockerfile
    environment:  
      DATABASE_HOST: 'postgres'
      DATABASE_PASSWORD: 'P@ssword'
      DATABASE_USERNAME: 'postgres'
      DATABASE_NAME: 'prl'
      CONFIG_PATH: '/etc'
    ports: 
      - "8080:8080"
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - postgres
    command: ["./wait-for-db.sh", "postgres:5432", "--", "sh", "./dev-startup.sh"]

  postgres:
    image: postgres:12-alpine
    build: 
      context: .
      dockerfile: db.Dockerfile
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: "P@ssword"
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
      
  mailhog:
      image: mailhog/mailhog
      container_name: 'mailhog'
      ports:
        - "1025:1025"
        - "8025:8025"

volumes:
  api:
  pg_data: